USE TechShop

-- 1. 1. Write an SQL query to find out which customers have not placed any orders. 

SELECT CONCAT(FirstName + SPACE(1), LastName) as 'Customer Name'
FROM Customers
WHERE CustomerID NOT IN ( SELECT CustomerID 
                          FROM Orders
			              WHERE CustomerID is NOT NULL)

-- 2. Write an SQL query to find the total number of products available for sale.  

-- Total Products Count
SELECT SUM(QuantityInStock) AS 'Products Available For Sale'
FROM Inventory

-- Product Name with Quantity
SELECT p.ProductName, i.QuantityInStock 
FROM Products p
JOIN Inventory i
ON p.ProductID = i.ProductID

-- 3. Write an SQL query to calculate the total revenue generated by TechShop.  

-- Product Name with Revenue Generated
Select p.ProductName, od.Quantity * p.Price AS 'Revenue for Each Product'
FROM Products p
JOIN OrderDetails od
ON p.ProductID = od.ProductID

-- Total Revenue
Select SUM(od.Quantity * p.Price) AS 'Total Revenue'
FROM Products p
JOIN OrderDetails od
ON p.ProductID = od.ProductID

-- 4. Write an SQL query to calculate the average quantity ordered for products in a specific category. 

SELECT AVG(Quantity)
FROM OrderDetails
WHERE ProductID IN ( SELECT ProductID
                     FROM Products
					 WHERE Categories = 'E-Gadgets' )

-- 5. Write an SQL query to calculate the total revenue generated by a specific customer. 

SELECT c.CustomerID, CONCAT(c.FirstName+SPACE(1), c.LastName) AS 'Customer Name', o.TotalAmount
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
WHERE c.CustomerID IN ( SELECT CustomerID
                        FROM Customers
					    WHERE FirstName = 'Kiran' AND LastName = 'Raj' )

-- 6. Write an SQL query to find the customers who have placed the most orders. List their names and the number of orders they've placed. 

SELECT CONCAT(FirstName + SPACE(1), LastName) AS 'Customer Name', NumberOfOrders
FROM Customers
WHERE NumberOfOrders = ( SELECT MAX(NumberOfOrders)
                         FROM Customers )

-- 7. Write an SQL query to find the most popular product category, which is the one with the highest total quantity ordered across all orders. 

SELECT p.Categories, od.Quantity
FROM Products p
JOIN OrderDetails od
ON p.ProductID = od.ProductID
WHERE Quantity = ( SELECT MAX(Quantity)
                   FROM OrderDetails )

-- 8. Write an SQL query to find the customer who has spent the most money (highest total revenue) on electronic gadgets. List their name and total spending. 

SELECT CONCAT(c.FirstName, SPACE(1) + c.LastName) AS 'Customer Name', o.TotalAmount
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
WHERE o.CustomerID = (
	SELECT TOP 1 CustomerID
    FROM Orders
    GROUP BY CustomerID
    ORDER BY SUM(TotalAmount) DESC )

-- 9. Write an SQL query to calculate the average order value (total revenue divided by the number of orders) for all customers. 

SELECT c.CustomerID, o.TotalAmount / c.NumberOfOrders AS 'Average Order Value'
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID

-- 10.  Write an SQL query to find the total number of orders placed by each customer and list their names along with the order count.

SELECT FirstName + SPACE(1) + LastName AS 'Customer Name', (
	    SELECT COUNT(*) 
	    FROM Orders 
	    WHERE Orders.CustomerID = Customers.CustomerID )  AS Order_Count 
FROM Customers


